apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
type: opaque
data:
  MYSQL_ROOT_PASSWORD:  cGFzc3dvcmQ= # echo -n xxxxx | base64
  MYSQL_PASSWORD : ZGJwYXNzd29yZA==  # echo -n xxxxx | base64
